theme:
  font:
    text: Oxygen  # Disable default font to use custom
  logo: how-systems-work-logo.svg
  favicon: how-systems-work-logo.svg
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  palette:
    # light mode
    - primary: white
    - accent: black
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_name: HowSystemsWork?
plugins:
  - blog:
      blog_dir: "."
      post_dir: blog
      blog_toc: true

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - extra.css

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2024 <a href="https://www.howsystemswork.com">HowSystemsWork?</a>

draft_docs: |
  drafts/

