theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - toc.follow
  palette:
    # light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_name: HowSystemsWork
plugins:
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - extra.css

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js